### ISSUE TITLE
Using Quick D-NOISE causes new render to start in another window.

### ISSUE THREAD

**Issue by Mitsuma** [grantwilk/DNOISE#1]
Blender 2.79b (latest stable).
D-NOISE 1.0
Windows 10 64bit

When you render a frame usually the 3D Viewport changes to the Image Editor.
Like: https://i.imgur.com/9VYVlQB.png

When you then press Quick D-NOISE it does its magic and changes to the D-NOISE Export image.
https://i.imgur.com/Q4SAbUS.png

Now when you hit render again, like to see how it looks after with less samples for example.
It starts rendering in another windown in Blender.
In case of my scene it decided to change the timeline to a Image Editor
https://i.imgur.com/GeodIpJ.png

When I hit D-NOISE there it will clear the image in the first Image Editor and change the former timeline to the new Export Image.
https://i.imgur.com/uglmx08.png

Rendering again would then go back to the first Image Editor: 
https://i.imgur.com/O2lyamH.png
and so on: https://i.imgur.com/kVUDxDS.png

It should probably just keep it in the same Image Editor and not force Blender to take another window and change that to a new Image Editor.
I think it behaves this way because the exported image is basically opened in the current Image Editor, thus by default Blender does not touch it again (since its also not the "Render Result" anymore)
Not sure how it can be resolved though unless you can overwrite the Render Result but that might not be wanted.

**Comment by grantwilk** [comment]
Unfortunately this issue is unfixable in the 2.79 version of D-NOISE. However, it has been fixed and implemented in the 2.80 branch of D-NOISE v1.1. Marking this as closed!
