### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Joki3D** [grantwilk/DNOISE#10]
If You enable denoiser in right tab, then after rendering finishes it has 100% but it's not finished and lasts forever if I  click cancel Blender crashes.
If I don't enable anything and use quick denoise after rendering manually Blender crashes.

version: 2.79 (sub 6), branch: blender2.8, commit date: 2018-12-07 15:33, hash: 0eb61c799d0, type: Release
build date: 07/12/2018, 17:09
platform: Windows
graphic card nvidia gtx 970

**Comment by grantwilk** [comment]
A similar issues already exists here: https://github.com/grantwilk/DNOISE/issues/8
I will be working to fix this in the next D-NOISE update.
