### ISSUE TITLE
D-NOISE result not auto saved?

### ISSUE THREAD

**Issue by microfan100** [grantwilk/DNOISE#12]
In render window，after the frame rendered complete，the D-NOISE result not auto replaced the original result. So the output saved image is not denoise. I had checked the box.
Please help me .

**Comment by grantwilk** [comment]
Make sure you have the OptiX binaries installed. If they are not installed, D-NOISE will not denoise the images. If you're confused as to what I am talking about, visit the installation tab of the D-NOISE webpage. https://remingtongraphics.net/tools/d-noise/
