### ISSUE TITLE
D-Noise does not display new render after it has been run before.

### ISSUE THREAD

**Issue by calinaayumi** [grantwilk/DNOISE#14]
Hello Grant,

Thank you for writing this add-on. I am having a similar issue to the optix add-on, the denoiser does not seem to overwrite an previously denoised image in the D-Noise Result data block. (If the denoise is checked under scene settings to run after an render is complete. The Quick D-noise button works in this case.)

**Comment by grantwilk** [comment]
This issue already exists in issue https://github.com/grantwilk/DNOISE/issues/1. Thanks for reporting it still! I'm currently in the process of fixing this bug.

**Comment by calinaayumi** [comment]
I see. Thank you for replying. ^_^

2018年12月9日(日) 16:46 Grant Wilk <notifications@github.com>:
