### ISSUE TITLE
stereoscopic images

### ISSUE THREAD

**Issue by trepaning** [grantwilk/DNOISE#17]
![dnoise-01](https://user-images.githubusercontent.com/45747611/49709787-e8b69900-fbea-11e8-886f-90ef6a12ae14.jpg)
Stereoscopic render (top/bottom) is going along as normal

![dnoise-02](https://user-images.githubusercontent.com/45747611/49709816-fff58680-fbea-11e8-8c07-db375fe4e726.jpg)
Dnoise closes, image is no longer stereo

![dnoise-03](https://user-images.githubusercontent.com/45747611/49709836-0dab0c00-fbeb-11e8-926e-0456a1ac92d5.jpg)
Resulting image is not stereoscopic

![dnoise-04](https://user-images.githubusercontent.com/45747611/49709844-1865a100-fbeb-11e8-9ac4-340725b0a449.jpg)
viewport goes dark after saving image

DNoise working with stereoscopic would be awesome. It is already a game changer for monoscopic.

**Comment by grantwilk** [comment]
Unfortunately, stereoscopic support cannot be added because of the way Blenders Python API is built.

**Comment by trepaning** [comment]
Ok thanks, I thought it might be possible being stereoscopic images work with the included denoiser.

________________________________
