### ISSUE TITLE
Add Blender 2.80 support

### ISSUE THREAD

**Issue by grantwilk** [grantwilk/DNOISE#19]

**Comment by CGIHuang** [comment]
Does the version support Blender 2.8 now?

**Comment by grantwilk** [comment]
Nope. Issues are not updates.

**Comment by CGIHuang** [comment]
Ho~Thanks♪(･ω･)ﾉ

**Comment by grantwilk** [comment]
Blender 2.80 support has been implemented and will be available in D-NOISE v1.1.
