### ISSUE TITLE
Clicking Quick D-NOISE twice causes an error, deletes result.

### ISSUE THREAD

**Issue by Mitsuma** [grantwilk/DNOISE#2]
Blender 2.79b (latest stable)
DNOISE 1.0
Windows 10 64bit

Clicking the Quick D-NOISE button on a D-NOISE result again causes this error.
![blender_2018-12-08_03-36-18](https://user-images.githubusercontent.com/8568089/49680970-e6ddc000-fa9a-11e8-8361-47c94ad7ca03.png)

```
Traceback (most recent call last):
  File "C:\Users\Mitsuma\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\DNOISE\__init__.py", line 180, in execute
    runpostdenoiser()
  File "C:\Users\Mitsuma\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\DNOISE\__init__.py", line 80, in runpostdenoiser
    fmutils.load(SCRIPT_DIR, source_name, 'D-NOISE Export')
  File "C:\Users\Mitsuma\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\DNOISE\fmutils.py", line 51, in load
    bpy.data.images.load(filepath=os.path.join(directory, filename))
RuntimeError: Error: Cannot read 'C:\Users\Mitsuma\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\DNOISE\source.exr': No such file or directory


location: <unknown location>:-1
```

This deletes the D-NOISE result:
![2018-12-08_03-37-54](https://user-images.githubusercontent.com/8568089/49680981-0674e880-fa9b-11e8-8791-234fbca563b9.png)
The background image vanishes once it refreshes from moving or anything.

Not sure how many people try to quick D-NOISE on the D-NOISE result but thought I report it anyways.

**Comment by captGuimbal** [comment]
same for me

**Comment by grantwilk** [comment]
This error was caused because I used the wrong comparison operator to detect the image name. This bug has been fixed, and clicking the Quick D-NOISE button in this scenario will not do anything. This patch will be available in D-NOISE v1_1.
