### ISSUE TITLE
Error on lines 108,77,40

### ISSUE THREAD

**Issue by tamil-selvan-eaets** [grantwilk/DNOISE#24]
![screenshot 172](https://user-images.githubusercontent.com/45813181/49854114-33185f80-fe0f-11e8-949d-1d1f6da2b151.png)

I have rendered it and try to use the dnoiseit shows me error

Is that my system fault or my fault? or something else?

**Comment by grantwilk** [comment]
This issue is caused because of a poor method for saving imported images. I have implemented a fix for this and it will be released in D-NOISE v1.1. Marking this issue as closed.
