### ISSUE TITLE
error lines 180,80,51

### ISSUE THREAD

**Issue by liobenelli** [grantwilk/DNOISE#26]
Hello Thansk for addon, but no fun for me
Intel i7 3820
nvidia gtx 770
 
![error](https://user-images.githubusercontent.com/16541302/49886352-6b1ba480-fe07-11e8-984c-26fe314e7c57.png)

**Comment by grantwilk** [comment]
What types of files are you trying to run through here? Is it just a render result?

**Comment by jiriKuba** [comment]
Same here.
NVIDIA GeForce GTX 960
Intel Core i5-6500

**Comment by robtoll** [comment]
Same - 180, 80 & 51
Intel Code i7-6700K
NVIDIA GeForce GTX 960

**Comment by liobenelli** [comment]
> What types of files are you trying to run through here? Is it just a render result?

Hi, thanks for your reply, yes I am attaching the final render when I run the addon

**Comment by xpawelsky** [comment]
You should save render result before DNOISE. Worked for me

**Comment by grantwilk** [comment]
I believe I have fixed this issue, however having not been able to replicate this issue myself, I am unsure whether or not it has been confidently fixed. I will release the fix in D-NOISE v1.1 this Friday.

I'm closing this issue for now, but if it persists after updating to v1.1, then I encourage you to comment on this issue again or open a new one. Thanks for your help!
