### ISSUE TITLE
Quick D-NOISE on imported image not working correctly, bright image.

### ISSUE THREAD

**Issue by Mitsuma** [grantwilk/DNOISE#3]
Blender 2.79b (latest stable)
DNOISE 1.0
Windows 10 64bit

When I try to use Quick D-NOISe on an image I open it doesn't seem to work correctly.
Imported image:
![blender_2018-12-08_04-15-31](https://user-images.githubusercontent.com/8568089/49681313-ec89d480-fa9f-11e8-94bd-0a8b777564da.jpg)

After using Quick D-NOISE:
![blender_2018-12-08_04-15-34](https://user-images.githubusercontent.com/8568089/49681317-f90e2d00-fa9f-11e8-892a-1cb5b4e82765.jpg)

Tried a few images but results are the same, getting some brightened image back. 
Works fine for newly rendered images.
Not sure if I'm doing something wrong here, did it like the video showed.

**Comment by grantwilk** [comment]
This was caused because D-NOISE interpreted the image as an OPEN EXR image even though it wasn't. This bug has been fixed and will be available in D-NOISE v1_1!
