### ISSUE TITLE
GitHub repository is not up to date

### ISSUE THREAD

**Issue by Lissanro** [grantwilk/DNOISE#30]
I have considering creating some pull requests (add Linux support, one small bug fix, perhaps more in the future) but discovered that this repository contains old addon version (1.0) but there is 1.1 available, and this is what I use. Most important difference is that 1.1 works in Blender 2.80, so I'm not interested in 1.0 version.

If you would like to support both 2.79 and 2.80 versions of Blender, I suggest making a branch for 2.79, and then use master to develop 2.80 version (this would be similar to what Blender developers did recently). Alternatively, create a branch for 2.80 and keep master as is. Either way it is important to have most recent source code in the repository so others can contribute.

**Comment by TheDuckCow** [comment]
Plus 1 to this, I’ve also been contemplating working to add OSX support. I’m guessing if Linux is done it will be easy if not already ready for OSX. The two-branch approach works well, and agreeing with making master be the 2.8 branch is a good idea.

**Comment by grantwilk** [comment]
I'm currently home for the holidays and don't have access to my primary system. I'll be updating it as soon as I get back to school.

**Comment by grantwilk** [comment]
The repository is now up to date. I'll be closing this issue now! Cheers :)
