### ISSUE TITLE
D-NOISE 2.80 wont work (export) with an animation (png sequence)

### ISSUE THREAD

**Issue by Docci** [grantwilk/DNOISE#33]
I've tried turning on and off the d-noise settings and it still won't export the d-noised image / won't create a d-noise render layers window when rendering in a png sequence. In the same project file, it works with just rendering a single image.

**Comment by sjonsjine** [comment]
I tried to render a png sequence yesterday with the D-Noise and it rendered 3 or 4 frames then Blender crashed, tried it a couple of times! Now I have switched from PNG to TGA and it renders without crashes!

**Comment by sjonsjine** [comment]
weird, now have a 50% size rendering and it renders as a png sequence..
