### ISSUE TITLE
No difference on imported Photographs

### ISSUE THREAD

**Issue by DerFluep** [grantwilk/DNOISE#34]
Using the Denoiser on actual Photographs taken with my camera results in exactly the same image.
Loading a rendered picture denoises as expected.

Tryed it on different images but always the same result.
My best guess is the Optix Denoiser doesnt recognise the noisepattern?
Can someone else confirm this?

**Comment by grantwilk** [comment]
D-NOISE works really well when removing noise like film grain, however it does little to nothing when it comes to ISO noise. This is because the underlying AI denoiser was not trained on that type of noise, so it fails to remove it.

Marking this issue as closed. Thanks for reporting it!

**Comment by DerFluep** [comment]
Ah ok like I guessed :)

Thanks for clarifying it!
Gone is the dream of effortless noise reduction for my Photographs..
Anyway, it still works wonders for renderings :)

**Comment by grantwilk** [comment]
Hopefully I can train the denoiser to work better on a more diverse set of noise patterns in the future, so your effortless noise reduction can be a reality!
