### ISSUE TITLE
Advanced Options Don't Show on 2.80 Version

### ISSUE THREAD

**Issue by EmoryAhlberg** [grantwilk/DNOISE#35]
The Advanced Denoisers would not display on the 2.80 version for me, but showed up on version 2.79b.

**Comment by grantwilk** [comment]
Could you share what build of 2.80 you are using? I'm guessing the issue you are having is due to you using a different build of 2.80 that has a bug or a slightly different feature set than the others.

**Comment by EmoryAhlberg** [comment]
Sure! It's the most recent build. I downloaded it the day before yesterday.
