### ISSUE TITLE
Blender 2.8 won’t save image renders post D-Noise install

### ISSUE THREAD

**Issue by giacometti777** [grantwilk/DNOISE#36]
Since beginning using Remington Graphics’ D-Noise add-on I haven’t been able to get render images to export via the compositor or the Output Panel. Even when I remove the add-on the issue persists. Is it possible the add-on has broken this function somehow?

**Comment by grantwilk** [comment]
Have you tried deleting the D-NOISE nodes in the compositor?

It may be because D-NOISE relies on a file output node in the compositor to export extra passes. This output node may be clogging up the system.

**Comment by giacometti777** [comment]
Yes, the D-Noise node is deleted in the compositor! Will D-Noise still work without it? Is the plugin meant supposed to re-generate this node whenever its missing? My issue is that I literally can't get output from the Output tab working even with D-Noise uninstalled at this point so I think its left something hidden in my compositor or something?

**Comment by giacometti777** [comment]
Do you think you might consider building in support for file output in the compositor in the next version? I think that would help nail down the issues I'm having. As it is the addon is unusable for me because I am working on animations and need the file output process automated.
