### ISSUE TITLE
Critical bug in normal conversion 

### ISSUE THREAD

**Issue by jordanSautron** [grantwilk/DNOISE#37]
optix.py / toscreenspace : 

you get the camera rotation by camera.rotation_euler.to_quaternion()

But

If the user use quaternion mode for the camera rotation, the euler rotation will not be updated when the camera rotation change. In this case, you will get an invalid camera rotation and then, an invalid screen space normal image.

To be sure to get a valid rotation value, you can use camera.matrix_world.to_quaternion(),
because the object matrix is updated each time you update the object transformation.

hope this can help you :)

ps: sorry for my english

**Comment by grantwilk** [comment]
Thank you for the tip! I will do my best to implement this in the next version of D-NOISE!
