### ISSUE TITLE
"No such file or directory" when trying to denoise

### ISSUE THREAD

**Issue by Stranget0** [grantwilk/DNOISE#39]
![image](https://user-images.githubusercontent.com/22750053/51550585-f22f5400-1e6c-11e9-9453-b4d771283c6e.png)

And any reinstall (blender, addon or even manually deleting files) doesn't fix the problem

**Comment by LevelZed** [comment]
![image](https://user-images.githubusercontent.com/11257385/52076111-f95a0e80-259e-11e9-8fac-5e071106579b.png)
The same problem with baked textures.
Though the common scene render works fine.

**Comment by grantwilk** [comment]
What version of D-NOISE are you guys using?

**Comment by LevelZed** [comment]
It's 1.1.0 on my side.
Blender 2.79
Windows 8.1
Nvidia GTX 870M

**Comment by garyritchie** [comment]
Update: Changed image from relative to absolute path as a workaround.

---

Also affecting me here, using:

version: 2.80 (sub 44), branch: master, commit date: 2019-02-08 14:02, hash: 29922b6ff5f4, type: Release
build date: 08/02/2019, 06:14
platform: Windows (10)

DNOISE (version: (1, 1, 0)

**Comment by masalvador** [comment]
Same thing happens to me on 2.8 8ac0fef4dfd1 with Dnoise 1.1.0, Windows 10.

The absolute path workaround was useful, thank you!
