### ISSUE TITLE
Denoising produces rainbow artifacts at high(er) sample counts

### ISSUE THREAD

**Issue by jessey-git** [grantwilk/DNOISE#4]
Take the attached .blend
- Render at 8 squared samples (64) and notice a pretty good denoising result
- Render again at 16 squared samples (256) and notice a large-ish rainbow colored artifact right along the sharp edge of the test box in the area of green light

Using the HDR data option is somewhat better, however the overall color of the emission lights are way over saturated and do not match a ground-truth render at say 20 squared samples (400).

[dnoise-test.zip](https://github.com/grantwilk/DNOISE/files/2659413/dnoise-test.zip)

**Comment by grantwilk** [comment]
Unfortunately, this issue is not something that is in my control. This has to do with the way the underlying AI denoiser was trained. I have added a new enhancement issue (#20)  that may help with this though.
