### ISSUE TITLE
Installation OptiX percentaje not refresh

### ISSUE THREAD

**Issue by MarioLunaSG** [grantwilk/DNOISE#40]
I started to download OptiX Binaries an i found that the percetaje label while Binaries are downloading only updates when I enter or leave the "Remove OptiX Binaries" button with mouse. Nothing too big, but im thinking about user experience.

**Comment by grantwilk** [comment]
Hey Mario,

What version of D-NOISE are you using? This was previously an issue in the beta of the D-NOISE, but was fixed before it's initial release.

**Comment by MarioLunaSG** [comment]
I cant tell you right now, but at the time I created the issue I downloaded from official remington graphics website for blender 2.8.
