### ISSUE TITLE
More User Control Please?

### ISSUE THREAD

**Issue by Slippi1** [grantwilk/DNOISE#42]
Hello,

Generally, I would love to see more parameters for users to control the image. Whether this is reasonably implementable with optix? I don’t know that. 

I love emerging technology, such as AI denoising, especially when its being implemented in blender! However, this feature is severely lacking in customization and user control over the final image. This tool is great for viewing quick previews, but due to the lack of flexibility and user input, I can’t bring myself to use this in production. The way this feature is implemented is not consistent with the workflow of CGI and VFX rendering, where the user is given the responsibility and tools to get the best image possible. 

Thank you,
Simon Lewis

**Comment by grantwilk** [comment]
Unfortunately, there aren't many additional settings within the proprietary denoiser that I can add to the Blender implementation. You may want to check out the work that DeepBlender (@DeepBlender on Twitter) is doing with his AI denoiser though. His structure will be much more production-ready than D-NOISE is.

Marking this issue as closed!

**Comment by DeepBlender** [comment]
@Slippi1 please get in touch on Twitter, BlenderArtists or send an email. I am very interested to hear what kind of controls are missing for your workflow!
