### ISSUE TITLE
Whether to support NVIDIA TITAN V series GPUs?

### ISSUE THREAD

**Issue by DukeHuang985** [grantwilk/DNOISE#44]
I want to know if D-Noise supports NVIDIA TITAN V-Series GPUs.
At the moment, I have no way to test it, I hope I can get a description.
Thanks a lot!

**Comment by grantwilk** [comment]
Hey Duke,

The underlying AI denoiser will run on any NVIDIA GPU with a driver version of 418.00 or newer. You'll be able to find the drivers supported by any NVIDIA GPU on their [drivers page](https://www.geforce.com/drivers).

Marking this as closed, thanks for your interest!
