### ISSUE TITLE
Addon is broken.

### ISSUE THREAD

**Issue by CASHNOW** [grantwilk/DNOISE#45]
Looks like the most recent build as of this post (git.adfdae3fc2f4-windows64) has broken DNOISE. Throws off this error when attempting to enable.

![image](https://user-images.githubusercontent.com/36146531/55033985-79598f00-4fb8-11e9-9735-7cf0e636e5d3.png)

**Comment by grantwilk** [comment]
Thanks for the heads up! This is because Blender now enforces a naming convention for method names and D-NOISE does not support this convention. I will have D-NOISE up and running again as soon as possible.

Thanks for your patience!

**Comment by iDarkBloodx** [comment]
Hi, Just wondering how the update is traveling? had the same issue this morning when i tried to install it,
thanks

**Comment by CASHNOW** [comment]
oddly enough when I installed git.6815efc3ff85-windows64 to check out the build I had DNOISE enabled from an earlier build from where it still worked. DNOISE continued to operate normally. I did not dare to disable and reenable DNOISE to see if it breaks.
