### ISSUE TITLE
Image size limitation?

### ISSUE THREAD

**Issue by SBld84** [grantwilk/DNOISE#47]
Hello,
D-noise seems to not work with large size renders for me. For a classic 4:3 image, I did some tests starting at 1000x750px, and slightly increased the resolution. D-Noise worked like a charm until around 6100x4575px; above this size it didn't apply. I haven't found any information about this, is there a size limitation?
Thanks
Seba

**Comment by fooditron** [comment]
I, too, have a large image - 6k x 3k - and D-Noise doesn't do anything.
