### ISSUE TITLE
 Denoiser don't work with "Use Extra Passes" on Blender 2.8

### ISSUE THREAD

**Issue by duncan778** [grantwilk/DNOISE#48]
If turn "Use Extra Passes", then at the end of render the denoiser don`t run and I get noised picture. If run it manually by "Quick D-Noise" button, then I get a denoised picture without detail, similar with "Use Extra Passes" is turn off.

![2019-04-20_22-58-58](https://user-images.githubusercontent.com/5847984/56461718-16dd8e00-63c0-11e9-9950-00220043ae96.png)

But if I open an empty Blender with startup settings, then all work fine:

![2019-04-21_10-43-12](https://user-images.githubusercontent.com/5847984/56467138-a5cfc200-6423-11e9-9f0f-db774f11332e.png)

...O-o-o,  I understand. Denoiser create nodes in View Layer, but in my scenes exist one more layer - Render Layer.  So to resolve my problem I need to delete Render Layer. Now it`s Ok.

**Comment by spiffy14k** [comment]
yo dude. im having the exact same problem. can you explain in more detail how you fixed it. what are the extra nodes connected to the D noise render layer node? what are you deleting? when i delete the render layer and replace it with the D noise render layer there is no difference.

**Comment by duncan778** [comment]
Hi! If you ported blend file from 2.79 to 2.80, then you have a Render layer in your scene. So you need to delete this layer, and, as result, the only View layer must be in the scene.
![2019-06-01_09-07-52](https://user-images.githubusercontent.com/5847984/58744590-83cb5580-844d-11e9-9222-1de1184bc40e.png)
No need any actions in the compositor.

**Comment by spiffy14k** [comment]
thanks for replying! that pretty much worked except i have to respawn the D noise compositor nodes in by double clicking the extra passes button. not sure why this is but it works so im happy 👍
