### ISSUE TITLE
Nice wrapper, but no mentioning?

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [grantwilk/DNOISE#6]
You know, when you use other people software it is usually nice to at least acknowledge it

https://github.com/DeclanRussell/NvidiaAIDenoiser

**Comment by Mitsuma** [comment]
![chrome_2018-12-08_15-01-42](https://user-images.githubusercontent.com/8568089/49686799-31daf000-fafa-11e8-9e57-03a4e4ca539e.png)

?

**Comment by grantwilk** [comment]
You'll also be able to find an acknowledgement to Declan's work on the actual add-on web page. 
![image](https://user-images.githubusercontent.com/37308267/49687906-dbf15280-facf-11e8-813f-135034c3191b.png)

I appreciate your concern, and I agree that you should acknowledge people if you use their software. Marking this issue as closed, thanks!
