### ISSUE TITLE
Blender 2.82.7 - I can't Install OptiX Binaries

### ISSUE THREAD

**Issue by VaneSlasher** [grantwilk/DNOISE#64]
Despite pressing the button nothing happens, can you help me?

**Comment by davidKertesz** [comment]
I'm experiencing this issue as well.

**Comment by Taapo** [comment]
Same here.

**Comment by C64Gamer** [comment]
Download:
[d-noise.zip](https://github.com/grantwilk/d-noise/files/4396617/d-noise.zip)

I have fixed the plugin for now. Have uploaded the binarys on a free file hoster page. File will be there for around 14 days. 

Delete the old installation and import this new zipfile from my comment.
You have to click on "Install OptiX Binarys" in the plugin options after the import.

!IMPORTANT!
1. There is no download progress bar but wait until the installation is done. It is a 243MB File. This takes some time.

2. Blender 2.8.x is why ever not able to execute it by default if you enable it in the settings. I was able to fix it over the "composer" tab. You have to add the dnoise component between "Render Layers" and "Composite":

![Screenshot_81](https://user-images.githubusercontent.com/13532609/77814833-11e78b00-70b5-11ea-9045-0d47023f49bb.png)

Works!

ps. Hope that the author from this really great plugin is fixing it soon. :-)

**Comment by alex-tolson** [comment]
I am also unable to get OptiX Binaries to install in Blender 2.79b or 2.82.  My OS is Windows 10.  The link to the files says, "The download quota for this file has been exceeded."  

Is there another way to download the files?

**Comment by Two-Tone** [comment]
> ps. Hope that the author from this really great plugin is fixing it soon. :-)

If the fact that this was closed is anything to go by, @grantwilk won't.  He keeps saying that it was depreciated in favor of the built in solution that came with 2.8.2, but always ignores the fact that most Nvidia users don't have an RTX card.
