### ISSUE TITLE
D-noiser

### ISSUE THREAD

**Issue by Blu-55** [grantwilk/DNOISE#70]
when I click the install button its not work I try it with Nvidia. And amd gpu

**Comment by sai2232** [comment]
i press the Optix Binaries but there is no prossing

**Comment by RickBioInf** [comment]
The add-on doesn't work. I think it is because your OptiX binaries download URL has changed and you haven't changed the code. Please do so, I do not know the right URL otherwise I would've done it.

**Comment by grantwilk** [comment]
Hi all,
I am no longer supporting D-NOISE and this repository is being archived since OptiX denoising is now natively supported in Blender. Thank you for your interest in D-NOISE.

Closing this issue and marking as wontfix.
